version: '2.1'
orbs:
  angular-npm-orb: 'code0987/angular-npm-orb@dev:alpha'
workflows:
  use-my-orb:
    jobs:
      - angular-npm-orb/test:
          e2e: false
          project: example-angular-library
          test: true
      - angular-npm-orb/build:
          project: example-angular-library
          requires:
            - angular-npm-orb/test
      - angular-npm-orb/publish:
          access: public
          environment:
            NPM_EMAIL: ...
            NPM_REGISTRY: 'https://registry.npmjs.org'
            NPM_TOKEN: ...
          path: dist/example-angular-library
          requires:
            - angular-npm-orb/build
